-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBVDjGfOoJ+rW9mniB/YT9ot7ItoOBDcZ30qypEwbISugCgYIKoZIzj0DAQehRANCAAT5AoGANW2yx1IPF6Oukz3SJODzqS2LwroiqxRWjQDEQ5bqiU75rqqVOnC0turtikl45bWwV4tRZ9wsswKu3Cca
-----END PRIVATE KEY-----